// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCQnHUPj9a6XuLPeF419SrO_GmmjoN_IG8",
    authDomain: "compelling-weft-470708-n8.firebaseapp.com",
    databaseURL: "https://compelling-weft-470708-n8-default-rtdb.firebaseio.com",
    projectId: "compelling-weft-470708-n8",
    storageBucket: "compelling-weft-470708-n8.firebasestorage.app",
    messagingSenderId: "10498248483",
    appId: "1:10498248483:web:06ed48fb91d09e85304696",
    measurementId: "G-86K7NLHNZG"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQnHUPj9a6XuLPeF419SrO_GmmjoN_IG8',
    appId: '1:10498248483:web:06ed48fb91d09e85304696',
    messagingSenderId: '10498248483',
    projectId: 'compelling-weft-470708-n8',
    databaseURL: 'https://compelling-weft-470708-n8-default-rtdb.firebaseio.com',
    storageBucket: 'compelling-weft-470708-n8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA8wwYZgy4yP_znzbAVRTNqA7YJOdc7nk',
    appId: '1:530194632368:ios:15ce8b6588acb0e929b575',
    messagingSenderId: '530194632368',
    projectId: 'ai-spor-analiz-2024',
    databaseURL: 'https://ai-spor-analiz-2024-default-rtdb.firebaseio.com',
    storageBucket: 'ai-spor-analiz-2024.firebasestorage.app',
    iosClientId: '530194632368-kkfgqjf2tjtgc7f7jsd5fm9q3c2eo374.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiSporAnaliz',
  );

}