// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_XKn4Ziha1OVOoPfILYGDoDUhOMnoRac',
    appId: '1:530194632368:web:7d5f2c799db4322529b575',
    messagingSenderId: '530194632368',
    projectId: 'ai-spor-analiz-2024',
    authDomain: 'ai-spor-analiz-2024.firebaseapp.com',
    databaseURL: 'https://ai-spor-analiz-2024-default-rtdb.firebaseio.com',
    storageBucket: 'ai-spor-analiz-2024.firebasestorage.app',
    measurementId: 'G-DQQZVTCV9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTnCsqYC2cIaqgpaZiMPdhRarg2Id7h-8',
    appId: '1:530194632368:android:86a2e8c86a2db58f29b575',
    messagingSenderId: '530194632368',
    projectId: 'ai-spor-analiz-2024',
    databaseURL: 'https://ai-spor-analiz-2024-default-rtdb.firebaseio.com',
    storageBucket: 'ai-spor-analiz-2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA8wwYZgy4yP_znzbAVRTNqA7YJOdc7nk',
    appId: '1:530194632368:ios:15ce8b6588acb0e929b575',
    messagingSenderId: '530194632368',
    projectId: 'ai-spor-analiz-2024',
    databaseURL: 'https://ai-spor-analiz-2024-default-rtdb.firebaseio.com',
    storageBucket: 'ai-spor-analiz-2024.firebasestorage.app',
    iosClientId: '530194632368-kkfgqjf2tjtgc7f7jsd5fm9q3c2eo374.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiSporAnaliz',
  );

}